/**
 * Static demo data for the TravelXM Agent Portal.
 *
 * This is the frontend-only phase: everything the UI displays comes from
 * here. When the API is wired up, replace the exports of this module with
 * fetchers that return the same `lib/types.ts` shapes.
 */

import type {
  ActivityItem,
  Booking,
  Commission,
  CommissionAnalytics,
  CrmStatus,
  Customer,
  DashboardSummary,
  PaymentsDashboard,
  SupportTicket,
  TravelPackage,
} from "./types";

export const DASHBOARD_SUMMARY: DashboardSummary = {
  totalRevenue: 852500,
  activeBookings: 24,
  totalCommissions: 96400,
  totalCustomers: 141,
  agentTier: "Gold",
};

export const REVENUE_BY_MONTH = [
  { month: "Jan", value: 42000 },
  { month: "Feb", value: 38500 },
  { month: "Mar", value: 56000 },
  { month: "Apr", value: 49000 },
  { month: "May", value: 67000 },
  { month: "Jun", value: 72000 },
  { month: "Jul", value: 85000 },
  { month: "Aug", value: 91000 },
  { month: "Sep", value: 78000 },
  { month: "Oct", value: 94000 },
  { month: "Nov", value: 102000 },
  { month: "Dec", value: 118000 },
];

export const SPARKLINES: Record<string, number[]> = {
  revenue: [42, 38, 56, 49, 67, 72, 85, 91, 78, 94, 102, 118],
  bookings: [8, 12, 9, 14, 11, 17, 13, 19, 15, 22, 18, 24],
  commissions: [5, 4, 7, 6, 8, 9, 11, 12, 10, 13, 14, 16],
  customers: [85, 90, 87, 95, 102, 98, 108, 115, 110, 122, 130, 141],
};

export const BOOKING_FUNNEL = [
  { label: "Leads", value: 412, pct: 100, color: "#0A4D5C" },
  { label: "Inquiries", value: 287, pct: 70, color: "#1a6f84" },
  { label: "Quoted", value: 198, pct: 48, color: "#D4A24C" },
  { label: "Booked", value: 147, pct: 36, color: "#E87A5D" },
  { label: "Traveled", value: 89, pct: 22, color: "#7C5CFC" },
];

export const PACKAGES: TravelPackage[] = [
  {
    id: 1,
    name: "Bali Luxury Escape",
    destination: "Bali, Indonesia",
    description:
      "Seven nights of curated indulgence across Ubud and Uluwatu — private pool villas, temple sunrises, and a dedicated island concierge.",
    category: "Luxury",
    pricePerPerson: 2450,
    duration: 8,
    commissionRate: 12,
    rating: 4.9,
    reviewCount: 128,
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    isFeatured: true,
    highlights: [
      "Private pool villa in Ubud rainforest",
      "Sunrise trek at Mount Batur",
      "Uluwatu temple Kecak fire dance",
      "Floating breakfast experience",
      "Full-day island concierge",
      "Return private transfers",
    ],
  },
  {
    id: 2,
    name: "Maldives Overwater Dream",
    destination: "Maldives",
    description:
      "Five nights in an overwater villa with glass floors, house-reef snorkelling, and champagne sunset cruises on a private dhoni.",
    category: "Honeymoon",
    pricePerPerson: 5350,
    duration: 6,
    commissionRate: 15,
    rating: 5.0,
    reviewCount: 96,
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&q=80",
    isFeatured: true,
    highlights: [
      "Overwater villa with glass floor",
      "House-reef snorkelling",
      "Private sunset dhoni cruise",
      "Couples spa ritual",
      "All-inclusive dining plan",
      "Seaplane transfers included",
    ],
  },
  {
    id: 3,
    name: "Swiss Alpine Tour",
    destination: "Switzerland",
    description:
      "A rail-and-peak journey through Lucerne, Interlaken and Zermatt with Glacier Express panoramic seats and Matterhorn views.",
    category: "Adventure",
    pricePerPerson: 3900,
    duration: 10,
    commissionRate: 10,
    rating: 4.8,
    reviewCount: 84,
    imageUrl: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80",
    isFeatured: true,
    highlights: [
      "Glacier Express panoramic carriage",
      "Jungfraujoch — Top of Europe",
      "Zermatt car-free village stay",
      "Lake Lucerne paddle steamer",
      "Swiss Travel Pass included",
    ],
  },
  {
    id: 4,
    name: "Kyoto Cultural Journey",
    destination: "Kyoto, Japan",
    description:
      "Machiya townhouse stays, private tea ceremony, and dawn access to Fushimi Inari before the crowds — Japan at its most serene.",
    category: "Cultural",
    pricePerPerson: 3200,
    duration: 9,
    commissionRate: 11,
    rating: 4.7,
    reviewCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    isFeatured: false,
    highlights: [
      "Restored machiya townhouse stay",
      "Private tea ceremony with a master",
      "Dawn walk at Fushimi Inari",
      "Arashiyama bamboo grove by rickshaw",
      "Kaiseki dinner with maiko performance",
    ],
  },
  {
    id: 5,
    name: "Dubai Luxury Week",
    destination: "Dubai, UAE",
    description:
      "Sky-high suites, desert glamping under the stars, and a private yacht afternoon along the Marina — the full Dubai spectrum.",
    category: "Luxury",
    pricePerPerson: 4100,
    duration: 7,
    commissionRate: 13,
    rating: 4.9,
    reviewCount: 74,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    isFeatured: true,
    highlights: [
      "Burj-view suite accommodation",
      "Overnight desert glamping",
      "Private yacht Marina cruise",
      "Sky-dining experience",
      "VIP Burj Khalifa access",
    ],
  },
  {
    id: 6,
    name: "Santorini Sunset Romance",
    destination: "Santorini, Greece",
    description:
      "Cliffside cave suites in Oia, catamaran caldera cruises, and volcanic-sand beach days built for two.",
    category: "Honeymoon",
    pricePerPerson: 2890,
    duration: 6,
    commissionRate: 12,
    rating: 4.8,
    reviewCount: 143,
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&q=80",
    isFeatured: false,
    highlights: [
      "Cave suite with private plunge pool",
      "Catamaran caldera sunset cruise",
      "Santo Wines volcano tasting",
      "Private photoshoot in Oia",
    ],
  },
  {
    id: 7,
    name: "Kenya Safari Expedition",
    destination: "Masai Mara, Kenya",
    description:
      "Game drives at golden hour, luxury tented camps, and a sunrise balloon safari over the Mara plains.",
    category: "Wildlife",
    pricePerPerson: 4750,
    duration: 8,
    commissionRate: 14,
    rating: 4.9,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80",
    isFeatured: false,
    highlights: [
      "Big Five game drives",
      "Sunrise hot-air balloon safari",
      "Luxury tented camp with full board",
      "Maasai village cultural visit",
      "Bush breakfast on the plains",
    ],
  },
  {
    id: 8,
    name: "Paris & Loire Châteaux",
    destination: "Paris, France",
    description:
      "Four nights in Saint-Germain plus a chauffeured Loire Valley château trail with private tastings.",
    category: "Cultural",
    pricePerPerson: 3450,
    duration: 7,
    commissionRate: 10,
    rating: 4.6,
    reviewCount: 98,
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
    isFeatured: false,
    highlights: [
      "Boutique stay in Saint-Germain",
      "Skip-the-line Louvre with art historian",
      "Chauffeured Loire châteaux day",
      "Seine dinner cruise",
    ],
  },
  {
    id: 9,
    name: "Costa Rica Rainforest Trail",
    destination: "Costa Rica",
    description:
      "Zip-lines over cloud forest, volcano hot springs, and wildlife lodges from Arenal to Manuel Antonio.",
    category: "Adventure",
    pricePerPerson: 2150,
    duration: 9,
    commissionRate: 11,
    rating: 4.7,
    reviewCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?w=600&q=80",
    isFeatured: false,
    highlights: [
      "Cloud-forest zip-line circuit",
      "Arenal volcano hot springs",
      "Manuel Antonio wildlife walk",
      "White-water rafting (Class III)",
    ],
  },
  {
    id: 10,
    name: "Maldives Family Lagoon",
    destination: "Maldives",
    description:
      "Beach villas on a kids-love-it lagoon island: dolphin cruises, splash park, and a kids' club that gives parents a real holiday.",
    category: "Family",
    pricePerPerson: 3150,
    duration: 7,
    commissionRate: 12,
    rating: 4.8,
    reviewCount: 58,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    isFeatured: false,
    highlights: [
      "Two-bedroom beach villa",
      "Kids' club & splash park",
      "Dolphin-spotting cruise",
      "Family snorkelling safari",
    ],
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: 1,
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@example.com",
    phone: "+91 98200 12345",
    country: "India",
    notes: "Prefers beach destinations. Vegetarian meals. Anniversary in November.",
    totalBookings: 4,
    totalSpent: 18400,
    createdAt: "2024-03-12T09:30:00Z",
  },
  {
    id: 2,
    firstName: "James",
    lastName: "Whitfield",
    email: "james.whitfield@example.com",
    phone: "+44 7700 900123",
    country: "United Kingdom",
    notes: "Frequent honeymoon referrer — owns a wedding planning studio.",
    totalBookings: 6,
    totalSpent: 42300,
    createdAt: "2023-11-02T14:15:00Z",
  },
  {
    id: 3,
    firstName: "Aisha",
    lastName: "Khan",
    email: "aisha.khan@example.com",
    phone: "+971 50 123 4567",
    country: "UAE",
    totalBookings: 2,
    totalSpent: 9800,
    createdAt: "2024-06-21T11:00:00Z",
  },
  {
    id: 4,
    firstName: "Marco",
    lastName: "Rossi",
    email: "marco.rossi@example.com",
    phone: "+39 320 555 0100",
    country: "Italy",
    notes: "Adventure traveler. Asks for detailed day-by-day itineraries.",
    totalBookings: 3,
    totalSpent: 14250,
    createdAt: "2024-01-18T16:45:00Z",
  },
  {
    id: 5,
    firstName: "Emily",
    lastName: "Chen",
    email: "emily.chen@example.com",
    phone: "+1 415 555 0132",
    country: "United States",
    totalBookings: 1,
    totalSpent: 5350,
    createdAt: "2025-02-05T10:20:00Z",
  },
  {
    id: 6,
    firstName: "Rahul",
    lastName: "Mehta",
    email: "rahul.mehta@example.com",
    phone: "+91 99870 45678",
    country: "India",
    notes: "Travels with extended family — needs connecting rooms.",
    totalBookings: 5,
    totalSpent: 27600,
    createdAt: "2023-08-30T08:05:00Z",
  },
  {
    id: 7,
    firstName: "Sofia",
    lastName: "Almeida",
    email: "sofia.almeida@example.com",
    phone: "+351 912 345 678",
    country: "Portugal",
    totalBookings: 2,
    totalSpent: 7040,
    createdAt: "2024-09-14T13:40:00Z",
  },
  {
    id: 8,
    firstName: "Daniel",
    lastName: "Okafor",
    email: "daniel.okafor@example.com",
    phone: "+234 803 555 0190",
    country: "Nigeria",
    notes: "Interested in safari packages for a company retreat.",
    totalBookings: 1,
    totalSpent: 4750,
    createdAt: "2025-04-22T15:10:00Z",
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: 1041,
    customerId: 2,
    customerName: "James Whitfield",
    packageName: "Maldives Overwater Dream",
    destination: "Maldives",
    startDate: "2026-09-04",
    endDate: "2026-09-10",
    travelers: 2,
    totalAmount: 10700,
    status: "confirmed",
  },
  {
    id: 1040,
    customerId: 1,
    customerName: "Priya Sharma",
    packageName: "Bali Luxury Escape",
    destination: "Bali, Indonesia",
    startDate: "2026-08-22",
    endDate: "2026-08-30",
    travelers: 2,
    totalAmount: 4900,
    status: "active",
  },
  {
    id: 1039,
    customerId: 6,
    customerName: "Rahul Mehta",
    packageName: "Dubai Luxury Week",
    destination: "Dubai, UAE",
    startDate: "2026-10-12",
    endDate: "2026-10-19",
    travelers: 5,
    totalAmount: 20500,
    status: "pending",
  },
  {
    id: 1038,
    customerId: 4,
    customerName: "Marco Rossi",
    packageName: "Swiss Alpine Tour",
    destination: "Switzerland",
    startDate: "2026-09-18",
    endDate: "2026-09-28",
    travelers: 2,
    totalAmount: 7800,
    status: "confirmed",
  },
  {
    id: 1037,
    customerId: 3,
    customerName: "Aisha Khan",
    packageName: "Santorini Sunset Romance",
    destination: "Santorini, Greece",
    startDate: "2026-07-02",
    endDate: "2026-07-08",
    travelers: 2,
    totalAmount: 5780,
    status: "completed",
  },
  {
    id: 1036,
    customerId: 8,
    customerName: "Daniel Okafor",
    packageName: "Kenya Safari Expedition",
    destination: "Masai Mara, Kenya",
    startDate: "2026-11-06",
    endDate: "2026-11-14",
    travelers: 1,
    totalAmount: 4750,
    status: "pending",
  },
  {
    id: 1035,
    customerId: 5,
    customerName: "Emily Chen",
    packageName: "Maldives Overwater Dream",
    destination: "Maldives",
    startDate: "2026-06-10",
    endDate: "2026-06-16",
    travelers: 1,
    totalAmount: 5350,
    status: "completed",
  },
  {
    id: 1034,
    customerId: 7,
    customerName: "Sofia Almeida",
    packageName: "Kyoto Cultural Journey",
    destination: "Kyoto, Japan",
    startDate: "2026-08-15",
    endDate: "2026-08-24",
    travelers: 2,
    totalAmount: 6400,
    status: "traveling",
  },
  {
    id: 1033,
    customerId: 1,
    customerName: "Priya Sharma",
    packageName: "Costa Rica Rainforest Trail",
    destination: "Costa Rica",
    startDate: "2026-05-03",
    endDate: "2026-05-12",
    travelers: 3,
    totalAmount: 6450,
    status: "cancelled",
  },
];

export const ACTIVITY: ActivityItem[] = [
  {
    id: 1,
    description: "Booking confirmed for Maldives Overwater Dream",
    customerName: "James Whitfield",
    createdAt: "2026-08-13T16:42:00Z",
    amount: 1605,
  },
  {
    id: 2,
    description: "Payment link opened by customer",
    customerName: "Rahul Mehta",
    createdAt: "2026-08-13T11:15:00Z",
  },
  {
    id: 3,
    description: "New lead added from website enquiry",
    customerName: "Daniel Okafor",
    createdAt: "2026-08-12T18:30:00Z",
  },
  {
    id: 4,
    description: "Commission earned — Santorini Sunset Romance",
    customerName: "Aisha Khan",
    createdAt: "2026-08-12T09:05:00Z",
    amount: 694,
  },
  {
    id: 5,
    description: "Itinerary sent for Swiss Alpine Tour",
    customerName: "Marco Rossi",
    createdAt: "2026-08-11T15:20:00Z",
  },
  {
    id: 6,
    description: "Support ticket resolved — seat upgrade request",
    customerName: "Sofia Almeida",
    createdAt: "2026-08-10T12:55:00Z",
  },
];

export const COMMISSIONS: Commission[] = [
  { id: 501, bookingId: 1041, amount: 1605, status: "earned", earnedAt: "2026-08-13" },
  { id: 500, bookingId: 1040, amount: 588, status: "pending", earnedAt: "2026-08-05" },
  { id: 499, bookingId: 1038, amount: 780, status: "earned", earnedAt: "2026-07-28" },
  { id: 498, bookingId: 1037, amount: 694, status: "paid", earnedAt: "2026-07-10" },
  { id: 497, bookingId: 1035, amount: 803, status: "paid", earnedAt: "2026-06-18" },
  { id: 496, bookingId: 1034, amount: 704, status: "earned", earnedAt: "2026-08-01" },
  { id: 495, bookingId: 1033, amount: 710, status: "pending", earnedAt: "2026-05-06" },
  { id: 494, bookingId: 1032, amount: 962, status: "paid", earnedAt: "2026-04-22" },
];

export const COMMISSION_ANALYTICS: CommissionAnalytics = {
  agentTier: "Gold",
  totalEarned: 96400,
  pendingAmount: 1298,
  thisMonth: 2897,
  nextPayoutDate: "2026-08-21",
  monthlyBreakdown: [
    { month: "Mar", amount: 1850 },
    { month: "Apr", amount: 2300 },
    { month: "May", amount: 1980 },
    { month: "Jun", amount: 2650 },
    { month: "Jul", amount: 3120 },
    { month: "Aug", amount: 2897 },
  ],
};

export const SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 88,
    subject: "Payment link expired before customer paid",
    message:
      "I generated a payment link for booking #1039 but my client says it had expired when they opened it two days later. Can links be extended?",
    priority: "high",
    category: "payment",
    status: "in_progress",
    createdAt: "2026-08-11T10:30:00Z",
  },
  {
    id: 87,
    subject: "Add a second traveler to booking #1036",
    message:
      "My client wants to bring a colleague on the Kenya safari. How do I add a traveler and re-quote without cancelling?",
    priority: "medium",
    category: "booking",
    status: "open",
    createdAt: "2026-08-09T14:05:00Z",
  },
  {
    id: 86,
    subject: "Commission rate on featured packages",
    message:
      "The Maldives package shows 15% but my statement calculated 12%. Which rate applies for Gold tier?",
    priority: "medium",
    category: "payment",
    status: "resolved",
    createdAt: "2026-08-04T09:15:00Z",
  },
  {
    id: 85,
    subject: "Cannot upload passport scans",
    message: "The upload spinner runs forever on the customer profile page. Tried Chrome and Safari.",
    priority: "low",
    category: "technical",
    status: "closed",
    createdAt: "2026-07-28T17:50:00Z",
  },
];

export const PAYMENTS_DASHBOARD: PaymentsDashboard = {
  availableBalance: 482050,
  pendingBalance: 129800,
  currency: "usd",
  totalCollected: 8525000,
  successfulPayments: 63,
  failedPayments: 4,
  pendingPayments: 3,
  recentTransactions: [
    {
      id: "pi_3Nx1a2b3c4d5e6f1",
      amount: 1070000,
      currency: "usd",
      status: "succeeded",
      description: "Maldives Overwater Dream — booking #1041",
      customerEmail: "james.whitfield@example.com",
      createdAt: "2026-08-13T16:40:00Z",
    },
    {
      id: "pi_3Nx1a2b3c4d5e6f2",
      amount: 490000,
      currency: "usd",
      status: "succeeded",
      description: "Bali Luxury Escape — booking #1040",
      customerEmail: "priya.sharma@example.com",
      createdAt: "2026-08-05T12:10:00Z",
    },
    {
      id: "pi_3Nx1a2b3c4d5e6f3",
      amount: 2050000,
      currency: "usd",
      status: "requires_action",
      description: "Dubai Luxury Week — booking #1039",
      customerEmail: "rahul.mehta@example.com",
      createdAt: "2026-08-13T11:12:00Z",
    },
    {
      id: "pi_3Nx1a2b3c4d5e6f4",
      amount: 780000,
      currency: "usd",
      status: "succeeded",
      description: "Swiss Alpine Tour — booking #1038",
      customerEmail: "marco.rossi@example.com",
      createdAt: "2026-07-27T09:45:00Z",
    },
    {
      id: "pi_3Nx1a2b3c4d5e6f5",
      amount: 475000,
      currency: "usd",
      status: "processing",
      description: "Kenya Safari Expedition — booking #1036",
      customerEmail: "daniel.okafor@example.com",
      createdAt: "2026-08-12T19:02:00Z",
    },
    {
      id: "pi_3Nx1a2b3c4d5e6f6",
      amount: 640000,
      currency: "usd",
      status: "succeeded",
      description: "Kyoto Cultural Journey — booking #1034",
      customerEmail: "sofia.almeida@example.com",
      createdAt: "2026-07-30T08:25:00Z",
    },
    {
      id: "pi_3Nx1a2b3c4d5e6f7",
      amount: 645000,
      currency: "usd",
      status: "requires_payment_method",
      description: "Costa Rica Rainforest Trail — booking #1033",
      customerEmail: "priya.sharma@example.com",
      createdAt: "2026-05-01T15:35:00Z",
    },
  ],
};

export const CRM_STATUS: CrmStatus = {
  totalSynced: 14,
  totalFailed: 1,
  records: [
    { entityType: "customer", portalId: 1, crmId: "zcrm_4876543210001", syncStatus: "synced", lastSyncedAt: "2026-08-13T16:45:00Z" },
    { entityType: "customer", portalId: 2, crmId: "zcrm_4876543210002", syncStatus: "synced", lastSyncedAt: "2026-08-13T16:45:00Z" },
    { entityType: "customer", portalId: 3, crmId: "zcrm_4876543210003", syncStatus: "synced", lastSyncedAt: "2026-08-13T16:45:00Z" },
    { entityType: "customer", portalId: 4, crmId: "zcrm_4876543210004", syncStatus: "synced", lastSyncedAt: "2026-08-12T10:20:00Z" },
    { entityType: "customer", portalId: 5, crmId: "zcrm_4876543210005", syncStatus: "synced", lastSyncedAt: "2026-08-12T10:20:00Z" },
    { entityType: "customer", portalId: 6, crmId: "zcrm_4876543210006", syncStatus: "synced", lastSyncedAt: "2026-08-12T10:20:00Z" },
    { entityType: "customer", portalId: 7, crmId: "zcrm_4876543210007", syncStatus: "synced", lastSyncedAt: "2026-08-11T09:00:00Z" },
    { entityType: "customer", portalId: 8, crmId: "", syncStatus: "failed", lastSyncedAt: "2026-08-11T09:00:00Z" },
    { entityType: "booking", portalId: 1041, crmId: "zcrm_deal_990001", syncStatus: "synced", lastSyncedAt: "2026-08-13T16:46:00Z" },
    { entityType: "booking", portalId: 1040, crmId: "zcrm_deal_990002", syncStatus: "synced", lastSyncedAt: "2026-08-05T12:15:00Z" },
    { entityType: "booking", portalId: 1039, crmId: "zcrm_deal_990003", syncStatus: "pending", lastSyncedAt: "2026-08-13T11:20:00Z" },
    { entityType: "booking", portalId: 1038, crmId: "zcrm_deal_990004", syncStatus: "synced", lastSyncedAt: "2026-07-27T09:50:00Z" },
    { entityType: "booking", portalId: 1037, crmId: "zcrm_deal_990005", syncStatus: "synced", lastSyncedAt: "2026-07-10T08:30:00Z" },
    { entityType: "booking", portalId: 1036, crmId: "zcrm_deal_990006", syncStatus: "synced", lastSyncedAt: "2026-08-12T19:05:00Z" },
    { entityType: "booking", portalId: 1035, crmId: "zcrm_deal_990007", syncStatus: "synced", lastSyncedAt: "2026-06-18T14:00:00Z" },
  ],
};

export const FEATURED_PACKAGES = PACKAGES.filter((p) => p.isFeatured);

export function getPackageById(id: number): TravelPackage | undefined {
  return PACKAGES.find((p) => p.id === id);
}

export function getCustomerById(id: number): Customer | undefined {
  return CUSTOMERS.find((c) => c.id === id);
}

export function getBookingsForCustomer(customerId: number): Booking[] {
  return BOOKINGS.filter((b) => b.customerId === customerId);
}
